[dev]
  targetPort = 8080
  # port = 8888 # Netlify Dev will run on this port (e.g. http://localhost:8888)
  # publish = "dist" # If your Vite build output is not 'dist'
  # command = "npm run dev" # If you need to customize the dev command

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
