[dev]
  targetPort = 8080
  port = 3000  # Match your development server port
  publish = "dist"
  command = "npm run dev"
  framework = "#custom"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://maps.googleapis.com https://storage.ko-fi.com https://ko-fi.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self' http://localhost:3000 https://*.netlify.app https://api.netlify.com https://gnews.io https://api.gnews.io https://ko-fi.com; frame-src https://www.google.com https://www.youtube.com https://ko-fi.com;"

# Handle form submissions
[[redirects]]
  from = "/"
  status = 200
  to = "/index.html"
  force = true
  conditions = {Role = ["bot", "crawler"]}

# Handle client-side routing - must come last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
