import React from 'react';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Your Privacy, Our Priority</h1>
      <p className="mb-4 text-sm text-gray-600">Last updated: August 18, 2024</p>

      <p className="mb-4">
        At Ternafit, we don’t just respect your privacy; we cherish it. Our Privacy Policy outlines our
        steadfast commitment to protecting your personal information.
      </p>
      <p className="mb-4">
        This Privacy Policy describes our policies and procedures on the collection, use, and disclosure
        of your information when you use the Service and informs you of your privacy rights and how the
        law protects you.
      </p>
      <p className="mb-6">
        We use your Personal Data to provide and improve the Service. By using the Service, you agree to
        the collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>
      <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
      <p className="mb-4">
        The words in which the initial letter is capitalized have meanings defined under the following
        conditions. The following definitions shall have the same meaning regardless of whether they
        appear in singular or plural form.
      </p>

      <h3 className="text-xl font-semibold mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>
          <strong>Account:</strong> A unique account created for you to access our Service or parts of
          our Service.
        </li>
        <li>
          <strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common
          control with a party, where “control” means ownership of 50% or more of the shares, equity
          interest, or other securities entitled to vote for election of directors or other managing
          authority.
        </li>
        <li>
          <strong>Organization:</strong> (referred to as either “the Organization”, “We”, “Us”, or
          “Our” in this Agreement) refers to Ternafit, Jungfrugatan 1F, 64131, Katrineholm, Sweden.
        </li>
        <li>
          <strong>Cookies:</strong> Small files that are placed on your computer, mobile device, or any
          other device by a website, containing the details of your browsing history on that website
          among its many uses.
        </li>
        <li>
          <strong>Country:</strong> Refers to Sweden.
        </li>
        <li>
          <strong>Device:</strong> Any device that can access the Service, such as a computer,
          cellphone, or digital tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> Any information that relates to an identified or identifiable
          individual.
        </li>
        <li>
          <strong>Service:</strong> Refers to the Website.
        </li>
        <li>
          <strong>Service Provider:</strong> Any natural or legal person who processes data on behalf
          of the Organization. This refers to third-party companies or individuals employed by the
          Organization to facilitate the Service, provide the Service on behalf of the Organization,
          perform services related to the Service, or assist the Organization in analyzing how the
          Service is used.
        </li>
        <li>
          <strong>Usage Data:</strong> Data collected automatically, either generated by the use of the
          Service or from the Service infrastructure itself (for example, the duration of a page
          visit).
        </li>
        <li>
          <strong>Website:</strong> Refers to Ternafit, accessible from https://www.ternafit.org
        </li>
        <li>
          <strong>You:</strong> The individual accessing or using the Service, or the company, or other
          legal entity on behalf of which such individual is accessing or using the Service, as
          applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
      <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
      <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
      <p className="mb-4">
        While using our Service, we may ask you to provide us with certain personally identifiable
        information that can be used to contact or identify you. Personally identifiable information
        may include, but is not limited to:
      </p>
      <ul className="list-disc list-inside mb-4 ml-4">
        <li>Email address</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
      <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
      <p className="mb-4">
        Usage Data may include information such as your Device’s Internet Protocol address (e.g., IP
        address), browser type, browser version, the pages of our Service that you visit, the time and
        date of your visit, the time spent on those pages, unique device identifiers, and other
        diagnostic data.
      </p>
      <p className="mb-4">
        When you access the Service by or through a mobile device, we may collect certain information
        automatically, including, but not limited to, the type of mobile device you use, your mobile
        device unique ID, the IP address of your mobile device, your mobile operating system, the type
        of mobile Internet browser you use, unique device identifiers, and other diagnostic data.
      </p>
      <p className="mb-6">
        We may also collect information that your browser sends whenever you visit our Service or when
        you access the Service by or through a mobile device.
      </p>

      <h3 className="text-xl font-semibold mb-2">Tracking Technologies and Cookies</h3>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to track the activity on our Service and store
        certain information. Tracking technologies used may include beacons, tags, and scripts to
        collect and track information and to improve and analyze our Service. The technologies we use
        may include:
      </p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>
          <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on your Device.
          You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being
          sent. However, if you do not accept Cookies, you may not be able to use some parts of our
          Service. Unless you have adjusted your browser setting so that it will refuse Cookies, our
          Service may use Cookies.
        </li>
        <li>
          <strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain
          small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and
          single-pixel gifs) that permit the Organization, for example, to count users who have
          visited those pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying system and server
          integrity).
        </li>
      </ul>
      <p className="mb-4">
        Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on your personal
        computer or mobile device when you go offline, while Session Cookies are deleted as soon as you
        close your web browser.
      </p>
      <p className="mb-4">
        We use both Session and Persistent Cookies for the purposes set out below:
      </p>
      <ul className="list-disc list-inside mb-6 space-y-4">
        <li>
          <p><strong>Necessary / Essential Cookies</strong></p>
          <p>Type: Session Cookies</p>
          <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies are essential to provide you with services available through the
            Website and to enable you to use some of its features. They help to authenticate users and
            prevent fraudulent use of user accounts. Without these Cookies, the services that you have
            asked for cannot be provided, and we only use these Cookies to provide you with those
            services.
          </p>
        </li>
        <li>
          <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
        </li>
        <li>
          <p><strong>Functionality Cookies</strong></p>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies allow us to remember choices you make when you use the Website, such
            as remembering your login details or language preference. The purpose of these Cookies is
            to provide you with a more personal experience and to avoid you having to re-enter your
            preferences every time you use the Website.
          </p>
        </li>
      </ul>
      <p className="mb-6">
        For more information about the cookies we use and your choices regarding cookies, please visit
        our Cookies Policy or the Cookies section of our Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Use of Your Personal Data</h2>
      <p className="mb-4">The Organization may use Personal Data for the following purposes:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li>
          To manage Your Account: to manage your registration as a user of the Service. The Personal
          Data you provide can give you access to different functionalities of the Service that are
          available to you as a registered user.
        </li>
        <li>
          For the performance of a contract: the development, compliance, and undertaking of the
          purchase contract for the products, items, or services you have purchased or any other
          contract with Us through the Service.
        </li>
        <li>
          To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of
          electronic communication, such as a mobile application’s push notifications regarding updates
          or informative communications related to the functionalities, products, or contracted
          services, including security updates when necessary or reasonable for their implementation.
        </li>
        <li>
          To provide you with news, special offers, and general information about other goods,
          services, and events we offer that are similar to those that you have already purchased or
          inquired about unless you have opted not to receive such information.
        </li>
        <li>To manage Your requests: To attend to and manage your requests to us.</li>
        <li>
          For business transfers: We may use your information to evaluate or conduct a merger,
          divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some
          or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or
          similar proceeding, in which Personal Data held by us about our Service users is among the
          assets transferred.
        </li>
        <li>
          For other purposes: We may use your information for other purposes, such as data analysis,
          identifying usage trends, determining the effectiveness of our promotional campaigns, and
          evaluating and improving our Service, products, services, marketing, and your experience.
        </li>
      </ul>
      <p className="mb-4">We may share your personal information in the following situations:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>
          With Service Providers: We may share your personal information with Service Providers to
          monitor and analyze the use of our Service and to contact you.
        </li>
        <li>
          For business transfers: We may share or transfer your personal information in connection
          with, or during negotiations of, any merger, sale of Organization assets, financing, or
          acquisition of all or a portion of our business to another company.
        </li>
        <li>
          With Affiliates: We may share your information with our affiliates, in which case we will
          require those affiliates to honor this Privacy Policy. Affiliates include our parent
          organization and any other subsidiaries, joint venture partners, or other companies that we
          control or that are under common control with us.
        </li>
        <li>
          With business partners: We may share your information with our business partners to offer you
          certain products, services, or promotions.
        </li>
        <li>
          With other users: When you share personal information or otherwise interact in the public
          areas with other users, such information may be viewed by all users and may be publicly
          distributed outside.
        </li>
        <li>With your consent: We may disclose your personal information for any other purpose with your consent.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Retention of Your Personal Data</h2>
      <p className="mb-4">
        The Organization will retain Your Personal Data only for as long as is necessary for the
        purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the
        extent necessary to comply with our legal obligations (for example, if we are required to
        retain your data to comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies.
      </p>
      <p className="mb-6">
        The Organization will also retain Usage Data for internal analysis purposes. Usage Data is
        generally retained for a shorter period of time, except when this data is used to strengthen
        the security or to improve the functionality of Our Service, or We are legally obligated to
        retain this data for longer time periods.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Transfer of Your Personal Data</h2>
      <p className="mb-4">
        Your information, including Personal Data, is processed at the Organization’s operating offices
        and in any other places where the parties involved in the processing are located. It means that
        this information may be transferred to — and maintained on — computers located outside of Your
        state, province, country, or other governmental jurisdiction where the data protection laws may
        differ from those of Your jurisdiction.
      </p>
      <p className="mb-4">
        Your consent to this Privacy Policy followed by Your submission of such information represents
        Your agreement to that transfer.
      </p>
      <p className="mb-6">
        The Organization will take all steps reasonably necessary to ensure that Your data is treated
        securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will
        take place to an organization or a country unless there are adequate controls in place
        including the security of Your data and other personal information.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Delete Your Personal Data</h2>
      <p className="mb-4">
        You have the right to delete or request that We assist in deleting the Personal Data that We
        have collected about You.
      </p>
      <p className="mb-4">
        Our Service may give You the ability to delete certain information about You from within the
        Service.
      </p>
      <p className="mb-4">
        You may update, amend, or delete Your information at any time by signing in to Your Account, if
        you have one, and visiting the account settings section that allows you to manage Your personal
        information. You may also contact Us to request access to, correct, or delete any personal
        information that You have provided to Us.
      </p>
      <p className="mb-6">
        Please note, however, that We may need to retain certain information when we have a legal
        obligation or lawful basis to do so.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Disclosure of Your Personal Data</h2>
      <h3 className="text-xl font-semibold mb-2">Business Transactions</h3>
      <p className="mb-4">
        If the Organization is involved in a merger, acquisition, or asset sale, Your Personal Data
        may be transferred. We will provide notice before Your Personal Data is transferred and becomes
        subject to a different Privacy Policy.
      </p>

      <h3 className="text-xl font-semibold mb-2">Law Enforcement</h3>
      <p className="mb-4">
        Under certain circumstances, the Organization may be required to disclose Your Personal Data if
        required to do so by law or in response to valid requests by public authorities (e.g., a court
        or a government agency).
      </p>

      <h3 className="text-xl font-semibold mb-2">Other Legal Requirements</h3>
      <p className="mb-4">
        The Organization may disclose Your Personal Data in the good faith belief that such action is
        necessary to:
      </p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Organization</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Security of Your Personal Data</h2>
      <p className="mb-6">
        The security of Your Personal Data is important to Us, but remember that no method of
        transmission over the Internet, or method of electronic storage is 100% secure. While We
        strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee
        its absolute security.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Children’s Privacy</h2>
      <p className="mb-4">
        Our Service does not address anyone under the age of 13. We do not knowingly collect
        personally identifiable information from anyone under the age of 13. If You are a parent or
        guardian and You are aware that Your child has provided Us with Personal Data, please contact
        Us. If We become aware that We have collected Personal Data from anyone under the age of 13
        without verification of parental consent, We take steps to remove that information from Our
        servers.
      </p>
      <p className="mb-6">
        If We need to rely on consent as a legal basis for processing Your information and Your country
        requires consent from a parent, We may require Your parent’s consent before We collect and use
        that information.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Links to Other Websites</h2>
      <p className="mb-4">
        Our Service may contain links to other websites that are not operated by Us. If You click on a
        third-party link, You will be directed to that third party’s site. We strongly advise You to
        review the Privacy Policy of every site You visit.
      </p>
      <p className="mb-6">
        We have no control over and assume no responsibility for the content, privacy policies, or
        practices of any third-party sites or services.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Changes to this Privacy Policy</h2>
      <p className="mb-4">
        We may update Our Privacy Policy from time to time. We will notify You of any changes by
        posting the new Privacy Policy on this page.
      </p>
      <p className="mb-4">
        We will let You know via email and/or a prominent notice on Our Service, prior to the change
        becoming effective and update the “Last updated” date at the top of this Privacy Policy.
      </p>
      <p className="mb-6">
        You are advised to review this Privacy Policy periodically for any changes. Changes to this
        Privacy Policy are effective when they are posted on this page.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>By email: info@ternafit.org</li>
      </ul>
    </div>
  );
};

export default PrivacyPolicyPage;
